services:
  paland-admin:
    build:
      context: .
      dockerfile: Dockerfile
    image: paland-admin:latest
    container_name: paland-admin
    restart: unless-stopped
    ports:
      - "18888:18888"
    environment:
      - TZ=Asia/Shanghai
    # 如果后续接数据库、Redis等，在这里加 networks 或 depends_on