spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://192.168.101.100:3306/paland?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: 192.168.101.100
      port: 6379
      password: ${REDIS_PASSWORD}
      database: 0

  quartz:
    job-store-type: jdbc
    jdbc:
      # never 表示不让 spring 参与建表，所以只能手动建表
      initialize-schema: never
    properties:
      org:
        quartz:
          jobStore:
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            useProperties: false
            tablePrefix: QRTZ_
          scheduler:
            instanceName: PalandScheduler
            instanceId: AUTO

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

sa-token:
  token-name: satoken
  timeout: 2592000
  active-timeout: -1
  is-concurrent: true
  is-share: true

server:
  # 服务器的HTTP端口，默认为8088
  port: 18888
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值25
      min-spare: 30