spring:
  profiles:
    active: dev
  threads:
    virtual:
      enabled: true

  datasource:
    url: jdbc:mysql://192.168.2.100:3306/paland?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: 192.168.2.100
      port: 6379
      password: ${REDIS_PASSWORD}
      database: 0

  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never  # 手动建表，不自动初始化
    properties:
      org:
        quartz:
          scheduler:
            instanceName: PalandScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX # 显式指定持久化类
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true                             # 开启集群
            clusterCheckinInterval: 15000                 # 集群心跳间隔
            txIsolationLevelSerializable: true            # 开启序列化隔离级别防死锁
            useProperties: false
            # ！！！这里解决之前的 DataSource name not set 报错！！！
            # 当 job-store-type 是 jdbc 时，Spring 会自动把默认数据源绑定给 quartz
            # 但如果底层内核继续找别名，这里可以显式指定。在 Spring 托管下通常这一行可以不用配
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 20                               # 线程池并发数
            threadPriority: 5

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

sa-token:
  token-name: satoken
  timeout: 2592000
  active-timeout: -1
  is-concurrent: true
  is-share: true

server:
  # 服务器的HTTP端口，默认为8088
  port: 18888
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值25
      min-spare: 30